[env]
PROJECT_NAME = "strawchemy"
_.python.venv = { path = ".venv" }
_.file = ".env"

[tools]
jq = "latest"
pre-commit = "latest"
actionlint = "latest"
cocogitto = "latest"
tombi = "latest"
yq = "latest"
gh = "latest"

[vars]
local_pytest_options = "-n=auto -vv"
uv_run = "uv run --frozen"
pytest_coverage_options = "--cov-config=./pyproject.toml --cov=src --cov-report=html --cov-report=xml"
ci_uv_run_options = " --frozen --no-default-groups --only-group=nox"
ci_pytest_coverage_options = "--cov-config=./pyproject.toml --cov=src --junit-xml=./junit.xml -o junit_family=legacy"
cleanable_paths = '''{{
[
  ".nox",
  ".pytest_cache",
  ".ruff_cache",
  ".hypothesis",
  "build/",
  "dist/",
  ".eggs/",
  ".coverage",
  "coverage.xml",
  "coverage.json",
  "junit*.xml",
  "htmlcov/",
  "tests/.pytest_cache",
  "tests/**/.pytest_cache",
  ".mypy_cache",
  ".unasyncd_cache/",
  ".auto_pytabs_cache",
  "node_module",
] | join(sep=" ")
}}'''
