# serializer version: 1
# name: test_query_schemas[all_fields_order_by]
  '''
  input ColorAggregateMinMaxStringFieldsOrderBy {
    name: OrderByEnum
  }
  
  input ColorAggregateNumericFieldsOrderBy {
    name: OrderByEnum
  }
  
  input ColorAggregateOrderBy {
    count: OrderByEnum
    maxString: ColorAggregateMinMaxStringFieldsOrderBy
    minString: ColorAggregateMinMaxStringFieldsOrderBy
    sum: ColorAggregateNumericFieldsOrderBy
  }
  
  """Ordering options"""
  input ColorOrderBy {
    id: OrderByEnum
    fruitsAggregate: FruitAggregateOrderBy
    fruits: FruitOrderBy
    name: OrderByEnum
  }
  
  """GraphQL type"""
  type ColorType {
    id: UUID!
    fruitsAggregate: FruitAggregate!
  
    """Fetch objects from the FruitType collection"""
    fruits: [FruitType!]!
    name: String!
  }
  
  """Aggregation fields"""
  type FruitAggregate {
    avg: FruitNumericFields!
    count: Int
    max: FruitMinMaxFields!
    min: FruitMinMaxFields!
    stddev: FruitNumericFields!
    stddevPop: FruitNumericFields!
    stddevSamp: FruitNumericFields!
    sum: FruitSumFields!
    varPop: FruitNumericFields!
    varSamp: FruitNumericFields!
    variance: FruitNumericFields!
  }
  
  input FruitAggregateMinMaxStringFieldsOrderBy {
    name: OrderByEnum
  }
  
  input FruitAggregateNumericFieldsOrderBy {
    sweetness: OrderByEnum
  }
  
  input FruitAggregateOrderBy {
    avg: FruitAggregateNumericFieldsOrderBy
    count: OrderByEnum
    max: FruitAggregateNumericFieldsOrderBy
    maxString: FruitAggregateMinMaxStringFieldsOrderBy
    min: FruitAggregateNumericFieldsOrderBy
    minString: FruitAggregateMinMaxStringFieldsOrderBy
    stddev: FruitAggregateNumericFieldsOrderBy
    stddevPop: FruitAggregateNumericFieldsOrderBy
    stddevSamp: FruitAggregateNumericFieldsOrderBy
    sum: FruitAggregateNumericFieldsOrderBy
    varPop: FruitAggregateNumericFieldsOrderBy
    varSamp: FruitAggregateNumericFieldsOrderBy
    variance: FruitAggregateNumericFieldsOrderBy
  }
  
  type FruitMinMaxFields {
    name: String
    sweetness: Int
  }
  
  type FruitNumericFields {
    sweetness: Float
  }
  
  """Ordering options"""
  input FruitOrderBy {
    id: OrderByEnum
    name: OrderByEnum
    colorId: OrderByEnum
    colorAggregate: ColorAggregateOrderBy
    color: ColorOrderBy
    sweetness: OrderByEnum
  }
  
  type FruitSumFields {
    name: String
    sweetness: Int
  }
  
  """GraphQL type"""
  type FruitType {
    id: UUID!
    name: String!
    colorId: UUID
    color: ColorType!
    sweetness: Int!
  }
  
  enum OrderByEnum {
    ASC
    ASC_NULLS_FIRST
    ASC_NULLS_LAST
    DESC
    DESC_NULLS_FIRST
    DESC_NULLS_LAST
  }
  
  type Query {
    """Fetch objects from the FruitType collection"""
    fruit(orderBy: [FruitOrderBy!] = null): [FruitType!]!
  }
  
  scalar UUID
  '''
# ---
