# serializer version: 1
# name: test_query_schemas[exclude_and_override_type]
  '''
  """GraphQL type"""
  type ColorType {
    id: UUID!
    fruitsAggregate: FruitAggregate!
  
    """Fetch objects from the FruitType collection"""
    fruits: [FruitType!]!
    name: String!
  }
  
  """Aggregation fields"""
  type FruitAggregate {
    avg: FruitNumericFields!
    count: Int
    max: FruitMinMaxFields!
    min: FruitMinMaxFields!
    stddev: FruitNumericFields!
    stddevPop: FruitNumericFields!
    stddevSamp: FruitNumericFields!
    sum: FruitSumFields!
    varPop: FruitNumericFields!
    varSamp: FruitNumericFields!
    variance: FruitNumericFields!
  }
  
  type FruitMinMaxFields {
    sweetness: Int
  }
  
  type FruitNumericFields {
    sweetness: Float
  }
  
  type FruitSumFields {
    sweetness: Int
  }
  
  """GraphQL type"""
  type FruitType {
    sweetness: String!
    id: UUID!
    colorId: UUID
    color: ColorType!
  }
  
  type Query {
    fruit: FruitType!
  }
  
  scalar UUID
  '''
# ---
