'''
"""Aggregation fields"""
type ColorAggregate {
  count: Int
  max: ColorMinMaxFields!
  min: ColorMinMaxFields!
  sum: ColorSumFields!
}

input ColorAggregateMinMaxStringFieldsOrderBy {
  name: OrderByEnum
}

input ColorAggregateNumericFieldsOrderBy {
  name: OrderByEnum
}

input ColorAggregateOrderBy {
  count: OrderByEnum
  maxString: ColorAggregateMinMaxStringFieldsOrderBy
  minString: ColorAggregateMinMaxStringFieldsOrderBy
  sum: ColorAggregateNumericFieldsOrderBy
}

"""GraphQL type"""
type ColorMinMaxFields {
  name: String
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input ColorOrderBy {
  fruitsAggregate: FruitAggregateOrderBy
  fruits: FruitOrderBy
  name: OrderByEnum
  id: OrderByEnum
}

"""GraphQL type"""
type ColorSumFields {
  name: String
}

"""GraphQL type"""
type ColorType {
  fruitsAggregate: FruitAggregate!

  """Fetch objects from the FruitType collection"""
  fruits: [FruitType!]!
  name: String!
  id: UUID!
}

"""GraphQL type"""
type ContainerType1 {
  fruitsAggregate: FruitAggregate!

  """Fetch objects from the FruitType collection"""
  fruits(limit: Int = 100, offset: Int! = 0): [FruitType!]!
  vegetablesAggregate: VegetableAggregate!

  """Fetch objects from the VegetableType collection"""
  vegetables(orderBy: [VegetableOrderBy!] = null): [VegetableType!]!
  colorsAggregate: ColorAggregate!

  """Fetch objects from the ColorType collection"""
  colors: [ColorType!]!
  name: String!
  id: UUID!
}

"""GraphQL type"""
type ContainerType2 {
  fruitsAggregate: FruitAggregate!

  """Fetch objects from the FruitType collection"""
  fruits(limit: Int = 100, offset: Int! = 0, orderBy: [FruitOrderBy!] = null): [FruitType!]!
  vegetablesAggregate: VegetableAggregate!

  """Fetch objects from the VegetableType collection"""
  vegetables(limit: Int = 100, offset: Int! = 0): [VegetableType!]!
  colorsAggregate: ColorAggregate!

  """Fetch objects from the ColorType collection"""
  colors: [ColorType!]!
  name: String!
  id: UUID!
}

"""GraphQL type"""
type ContainerType3 {
  fruitsAggregate: FruitAggregate!

  """Fetch objects from the FruitType collection"""
  fruits(limit: Int = 100, offset: Int! = 0, orderBy: [FruitOrderBy!] = null): [FruitType!]!
  vegetablesAggregate: VegetableAggregate!

  """Fetch objects from the VegetableType collection"""
  vegetables(limit: Int = 100, offset: Int! = 0): [VegetableType!]!
  colorsAggregate: ColorAggregate!

  """Fetch objects from the ColorType collection"""
  colors(limit: Int = 100, offset: Int! = 0): [ColorType!]!
  name: String!
  id: UUID!
}

"""Aggregation fields"""
type FruitAggregate {
  avg: FruitNumericFields!
  count: Int
  max: FruitMinMaxFields!
  min: FruitMinMaxFields!
  stddevPop: FruitNumericFields!
  stddevSamp: FruitNumericFields!
  sum: FruitSumFields!
  varPop: FruitNumericFields!
  varSamp: FruitNumericFields!
}

input FruitAggregateMinMaxStringFieldsOrderBy {
  name: OrderByEnum
}

input FruitAggregateNumericFieldsOrderBy {
  sweetness: OrderByEnum
}

input FruitAggregateOrderBy {
  avg: FruitAggregateNumericFieldsOrderBy
  count: OrderByEnum
  max: FruitAggregateNumericFieldsOrderBy
  maxString: FruitAggregateMinMaxStringFieldsOrderBy
  min: FruitAggregateNumericFieldsOrderBy
  minString: FruitAggregateMinMaxStringFieldsOrderBy
  stddevPop: FruitAggregateNumericFieldsOrderBy
  stddevSamp: FruitAggregateNumericFieldsOrderBy
  sum: FruitAggregateNumericFieldsOrderBy
  varPop: FruitAggregateNumericFieldsOrderBy
  varSamp: FruitAggregateNumericFieldsOrderBy
}

"""GraphQL type"""
type FruitMinMaxFields {
  name: String
  sweetness: Int
}

"""GraphQL type"""
type FruitNumericFields {
  sweetness: Float
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input FruitOrderBy {
  colorAggregate: ColorAggregateOrderBy
  color: ColorOrderBy
  name: OrderByEnum
  colorId: OrderByEnum
  sweetness: OrderByEnum
  id: OrderByEnum
}

"""GraphQL type"""
type FruitSumFields {
  name: String
  sweetness: Int
}

"""GraphQL type"""
type FruitType {
  color: ColorType!
  name: String!
  colorId: UUID
  sweetness: Int!
  id: UUID!
}

enum OrderByEnum {
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
}

type Query {
  """Fetch objects from the ContainerType1 collection"""
  container1: [ContainerType1!]!

  """Fetch objects from the ContainerType2 collection"""
  container2: [ContainerType2!]!

  """Fetch objects from the ContainerType3 collection"""
  container3: [ContainerType3!]!
}

scalar UUID

"""Aggregation fields"""
type VegetableAggregate {
  count: Int
  max: VegetableMinMaxFields!
  min: VegetableMinMaxFields!
  sum: VegetableSumFields!
}

enum VegetableFamily {
  MUSHROOM
  GOURD
  CABBAGE
  ONION
  SEEDS
}

"""GraphQL type"""
type VegetableMinMaxFields {
  name: String
  description: String
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input VegetableOrderBy {
  family: OrderByEnum
  id: OrderByEnum
  name: OrderByEnum
  description: OrderByEnum
}

"""GraphQL type"""
type VegetableSumFields {
  name: String
  description: String
}

"""GraphQL type"""
type VegetableType {
  family: VegetableFamily!
  id: UUID!
  name: String!
  description: String!
}
'''