'''
"""Date with time (isoformat)"""
scalar DateTime

type Mutation {
  """Fetch object from the TimestampedRecordType collection by id"""
  createRecord(data: TimestampedRecordCreateInput!): TimestampedRecordType!
}

type Query {
  hello: String!
}

"""Create input"""
input TimestampedRecordCreateInput {
  id: Int!
  createdAt: DateTime
}

"""GraphQL type"""
type TimestampedRecordType {
  id: Int!
  createdAt: DateTime!
}
'''