'''
"""Aggregation fields"""
type ColorAggregate {
  count: Int
  max: ColorMinMaxFields!
  min: ColorMinMaxFields!
  sum: ColorSumFields!
}

input ColorAggregateOrderBy {
  count: OrderByEnum
}

"""GraphQL type"""
type ColorMinMaxFields {
  name: String
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input ColorOrderBy {
  fruitsAggregate: FruitAggregateOrderBy
  fruits: FruitOrderBy
  name: OrderByEnum
  id: OrderByEnum
}

"""GraphQL type"""
type ColorSumFields {
  name: String
}

"""GraphQL type"""
type ColorType {
  fruitsAggregate: FruitAggregate!

  """Fetch objects from the FruitType collection"""
  fruits: [FruitType!]!
  name: String!
  id: UUID!
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input ContainerOrderBy {
  fruitsAggregate: FruitAggregateOrderBy
  fruits: FruitOrderBy
  vegetablesAggregate: VegetableAggregateOrderBy
  vegetables: VegetableOrderBy
}

"""GraphQL type"""
type ContainerType {
  fruitsAggregate: FruitAggregate!

  """Fetch objects from the FruitType collection"""
  fruits: [FruitType!]!
  vegetablesAggregate: VegetableAggregate!

  """Fetch objects from the VegetableType collection"""
  vegetables: [VegetableType!]!
  colorsAggregate: ColorAggregate!

  """Fetch objects from the ColorType collection"""
  colors: [ColorType!]!
  name: String!
  id: UUID!
}

"""Aggregation fields"""
type FruitAggregate {
  avg: FruitNumericFields!
  count: Int
  max: FruitMinMaxFields!
  min: FruitMinMaxFields!
  stddevPop: FruitNumericFields!
  stddevSamp: FruitNumericFields!
  sum: FruitSumFields!
  varPop: FruitNumericFields!
  varSamp: FruitNumericFields!
}

input FruitAggregateOrderBy {
  count: OrderByEnum
}

"""GraphQL type"""
type FruitMinMaxFields {
  name: String
  sweetness: Int
}

"""GraphQL type"""
type FruitNumericFields {
  sweetness: Float
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input FruitOrderBy {
  colorAggregate: ColorAggregateOrderBy
  color: ColorOrderBy
  name: OrderByEnum
  colorId: OrderByEnum
  sweetness: OrderByEnum
  id: OrderByEnum
}

"""GraphQL type"""
type FruitSumFields {
  name: String
  sweetness: Int
}

"""GraphQL type"""
type FruitType {
  color: ColorType!
  name: String!
  colorId: UUID
  sweetness: Int!
  id: UUID!
}

enum OrderByEnum {
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
}

type Query {
  """Fetch objects from the ContainerType collection"""
  containers(orderBy: [ContainerOrderBy!] = null): [ContainerType!]!
}

scalar UUID

"""Aggregation fields"""
type VegetableAggregate {
  count: Int
  max: VegetableMinMaxFields!
  min: VegetableMinMaxFields!
  sum: VegetableSumFields!
}

input VegetableAggregateOrderBy {
  count: OrderByEnum
}

enum VegetableFamily {
  MUSHROOM
  GOURD
  CABBAGE
  ONION
  SEEDS
}

"""GraphQL type"""
type VegetableMinMaxFields {
  name: String
  description: String
}

"""
Boolean expression to compare fields. All fields are combined with logical 'AND'.
"""
input VegetableOrderBy {
  family: OrderByEnum
  id: OrderByEnum
  name: OrderByEnum
  description: OrderByEnum
}

"""GraphQL type"""
type VegetableSumFields {
  name: String
  description: String
}

"""GraphQL type"""
type VegetableType {
  family: VegetableFamily!
  id: UUID!
  name: String!
  description: String!
}
'''