[auto-bump]
description = "Auto bump the version"
confirm = "Are you sure you want to auto bump the version?"
depends = "uv:install"
run = "cog bump --auto --hook-profile manual"

[clean]
description = "Clean working directory"
alias = "c"
confirm = "Are you sure you want to clean the working directory? This will remove test caches, build artifacts, and other temporary files."
run = [
  "rm -rf {{vars.cleanable_paths}} >/dev/null 2>&1",
  "find . -name '*.egg-info' -exec rm -rf {} + >/dev/null 2>&1",
  "find . -type f -name '*.egg' -exec rm -f {} + >/dev/null 2>&1",
  "find . -name '*.pyc' -exec rm -f {} + >/dev/null 2>&1",
  "find . -name '*.pyo' -exec rm -f {} + >/dev/null 2>&1",
  "find . -name '*~' -exec rm -f {} + >/dev/null 2>&1",
  "find . -name '__pycache__' -exec rm -rf {} + >/dev/null 2>&1",
  "find . -name '.ipynb_checkpoints' -exec rm -rf {} + >/dev/null 2>&1",
]

["render:usage"]
description = "Generate tasks documentation"
run = ["mise generate task-docs > tasks.md"]
