"""Tests for the ``OffsetPagination`` pass: the root page subquery and what it exports."""

from __future__ import annotations

import pytest
from inline_snapshot import snapshot

from tests.unit.transpiler.passes.utils import plan_sql

_DIALECTS = pytest.mark.parametrize("dialect_name", ["postgresql", "sqlite", "mysql"])


@_DIALECTS
def test_pagination_wraps_and_counts_roots(dialect_name: str) -> None:
    """A limit runs in a page subquery of the root rows, and a selected to-many relation is joined outside it."""
    lines = plan_sql("{ colorsPaginated(limit: 2) { fruits { name } } }", dialect_name)

    assert (
        lines
        == snapshot(
            {
                "postgresql": [
                    "SELECT color.id,",
                    "       fruit_1.name,",
                    "       fruit_1.id AS id_1",
                    "  FROM (",
                    "        SELECT color.id AS id",
                    "          FROM color AS color",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %(param_1)s",
                    "        OFFSET %(param_2)s",
                    "       ) AS color",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC",
                ],
                "sqlite": [
                    "SELECT color.id,",
                    "       fruit_1.name,",
                    "       fruit_1.id AS id_1",
                    "  FROM (",
                    "        SELECT color.id AS id",
                    "          FROM color AS color",
                    "         ORDER BY color.id ASC",
                    "         LIMIT ?",
                    "        OFFSET ?",
                    "       ) AS color",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC",
                ],
                "mysql": [
                    "SELECT color.id,",
                    "       fruit_1.name,",
                    "       fruit_1.id AS id_1",
                    "  FROM (",
                    "        SELECT color.id AS id",
                    "          FROM color AS color",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %s,",
                    "               %s",
                    "       ) AS color",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC",
                ],
            }
        )[dialect_name]
    )


@_DIALECTS
@pytest.mark.parametrize(
    "query",
    [
        pytest.param(
            """{ colorsPaginated(limit: 2, orderBy: { fruitsAggregate: { sum: { sweetness: ASC } } }) {
                id fruitsAggregate { count } } }""",
            id="selected-function-hoisted",
        ),
        pytest.param(
            """{ colorsPaginated(limit: 2, filter: { fruitsAggregate: { count: { predicate: { gt: 1 } } } }) {
                id fruitsAggregate { sum { sweetness } } } }""",
            id="filtered-function-hoisted",
        ),
        pytest.param(
            """{ colorsPaginated(limit: 2, filter: { fruitsAggregate: {
                count: { predicate: { gt: 1 } }, sum: { arguments: [sweetness], predicate: { gt: 0 } } } }) {
                id fruitsAggregate { count sum { sweetness } } } }""",
            id="two-functions-filtered-and-selected",
        ),
    ],
)
def test_pagination_hoists_aggregate(dialect_name: str, query: str, request: pytest.FixtureRequest) -> None:
    """An aggregate the paginated rows use is joined once, inside the page, and the outer query reads it from the page."""
    lines = plan_sql(query, dialect_name)

    assert (
        lines
        == snapshot(
            {
                "selected-function-hoisted-postgresql": [
                    "SELECT color.id,",
                    "       color.count_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.count_1 AS count_1,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          JOIN LATERAL (",
                    "                SELECT sum(fruit_1.sweetness) AS sum_1,",
                    "                       count(*) AS count_1",
                    "                  FROM fruit AS fruit_1",
                    "                 WHERE color.id = fruit_1.color_id",
                    "               ) AS anon_1",
                    "            ON TRUE",
                    "         ORDER BY anon_1.sum_1 ASC",
                    "         LIMIT %(param_1)s",
                    "        OFFSET %(param_2)s",
                    "       ) AS color",
                    " ORDER BY color.sum_1 ASC",
                ],
                "selected-function-hoisted-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT sum(fruit_1.sweetness) AS sum_1,",
                    "               count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(color.count_1, ?) AS coalesce_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.count_1 AS count_1,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         ORDER BY anon_1.sum_1 ASC",
                    "         LIMIT ?",
                    "        OFFSET ?",
                    "       ) AS color",
                    " ORDER BY color.sum_1 ASC",
                ],
                "selected-function-hoisted-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT sum(fruit_1.sweetness) AS sum_1,",
                    "               count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(color.count_1, %s) AS coalesce_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.count_1 AS count_1,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         ORDER BY anon_1.sum_1 ASC",
                    "         LIMIT %s,",
                    "               %s",
                    "       ) AS color",
                    " ORDER BY color.sum_1 ASC",
                ],
                "filtered-function-hoisted-postgresql": [
                    "SELECT color.id,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          JOIN LATERAL (",
                    "                SELECT count(*) AS count_1,",
                    "                       sum(fruit_1.sweetness) AS sum_1",
                    "                  FROM fruit AS fruit_1",
                    "                 WHERE color.id = fruit_1.color_id",
                    "               ) AS anon_1",
                    "            ON TRUE",
                    "         WHERE anon_1.count_1 > %(param_1)s",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %(param_2)s",
                    "        OFFSET %(param_3)s",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "filtered-function-hoisted-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         WHERE coalesce(anon_1.count_1, ?) > ?",
                    "         ORDER BY color.id ASC",
                    "         LIMIT ?",
                    "        OFFSET ?",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "filtered-function-hoisted-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         WHERE coalesce(anon_1.count_1, %s) > %s",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %s,",
                    "               %s",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "two-functions-filtered-and-selected-postgresql": [
                    "SELECT color.id,",
                    "       color.count_1,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.count_1 AS count_1,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          JOIN LATERAL (",
                    "                SELECT count(*) AS count_1,",
                    "                       sum(fruit_1.sweetness) AS sum_1",
                    "                  FROM fruit AS fruit_1",
                    "                 WHERE color.id = fruit_1.color_id",
                    "               ) AS anon_1",
                    "            ON TRUE",
                    "         WHERE anon_1.count_1 > %(param_1)s",
                    "           AND anon_1.sum_1 > %(param_2)s",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %(param_3)s",
                    "        OFFSET %(param_4)s",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "two-functions-filtered-and-selected-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(color.count_1, ?) AS coalesce_1,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.count_1 AS count_1,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         WHERE coalesce(anon_1.count_1, ?) > ?",
                    "           AND anon_1.sum_1 > ?",
                    "         ORDER BY color.id ASC",
                    "         LIMIT ?",
                    "        OFFSET ?",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "two-functions-filtered-and-selected-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(color.count_1, %s) AS coalesce_1,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.count_1 AS count_1,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         WHERE coalesce(anon_1.count_1, %s) > %s",
                    "           AND anon_1.sum_1 > %s",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %s,",
                    "               %s",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
            }
        )[request.node.callspec.id]
    )
