"""Tests for the ``Aggregations`` pass: selected aggregates of relations, read from the join computing them."""

from __future__ import annotations

import pytest
from inline_snapshot import snapshot

from tests.unit.transpiler.passes.utils import plan_sql

_DIALECTS = pytest.mark.parametrize("dialect_name", ["postgresql", "sqlite", "mysql"])


@_DIALECTS
@pytest.mark.parametrize(
    "query",
    [
        pytest.param(
            """{ colorsPaginated(limit: 2, filter: { fruitsAggregate: { count: { predicate: { gt: 1 } } } }) {
                id fruitsAggregate { sum { sweetness } } } }""",
            id="filter-only-paginated",
        ),
        pytest.param(
            """{ colors(filter: { fruitsAggregate: { count: { predicate: { gt: 1 } } } }) {
                id fruitsAggregate { sum { sweetness } } } }""",
            id="filter-only",
        ),
        pytest.param(
            """{ colors(orderBy: { fruitsAggregate: { avg: { sweetness: ASC } } }) {
                id fruitsAggregate { count } } }""",
            id="order-by-only",
        ),
        pytest.param(
            """{ colors(filter: { fruitsAggregate: { count: { predicate: { gt: 1 } } } }) {
                id fruitsAggregate { count } } }""",
            id="filtered-and-selected",
        ),
        pytest.param(
            """{ groups(filter: { color: { fruitsAggregate: { count: { predicate: { gt: 1 } } } } }) {
                id color { id fruitsAggregate { sum { sweetness } } } } }""",
            id="nested-filter-only",
        ),
    ],
)
def test_selects_only_requested_functions(dialect_name: str, query: str, request: pytest.FixtureRequest) -> None:
    """A function only the filter or the ordering needs is computed by the join but never reaches the SELECT list."""
    assert (
        plan_sql(query, dialect_name)
        == snapshot(
            {
                "filter-only-paginated-postgresql": [
                    "SELECT color.id,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          JOIN LATERAL (",
                    "                SELECT count(*) AS count_1,",
                    "                       sum(fruit_1.sweetness) AS sum_1",
                    "                  FROM fruit AS fruit_1",
                    "                 WHERE color.id = fruit_1.color_id",
                    "               ) AS anon_1",
                    "            ON TRUE",
                    "         WHERE anon_1.count_1 > %(param_1)s",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %(param_2)s",
                    "        OFFSET %(param_3)s",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "filter-only-paginated-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         WHERE coalesce(anon_1.count_1, ?) > ?",
                    "         ORDER BY color.id ASC",
                    "         LIMIT ?",
                    "        OFFSET ?",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "filter-only-paginated-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       color.sum_1",
                    "  FROM (",
                    "        SELECT color.id AS id,",
                    "               anon_1.sum_1 AS sum_1",
                    "          FROM color AS color",
                    "          LEFT OUTER JOIN anon_1",
                    "            ON color.id = anon_1.color_id",
                    "         WHERE coalesce(anon_1.count_1, %s) > %s",
                    "         ORDER BY color.id ASC",
                    "         LIMIT %s,",
                    "               %s",
                    "       ) AS color",
                    " ORDER BY color.id ASC",
                ],
                "filter-only-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.sum_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " WHERE anon_1.count_1 > %(param_1)s",
                    " ORDER BY color.id ASC",
                ],
                "filter-only-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       anon_1.sum_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, ?) > ?",
                    " ORDER BY color.id ASC",
                ],
                "filter-only-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       anon_1.sum_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, %s) > %s",
                    " ORDER BY color.id ASC",
                ],
                "order-by-only-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.count_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT avg(fruit_1.sweetness) AS avg_1,",
                    "               count(*) AS count_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " ORDER BY anon_1.avg_1 ASC",
                ],
                "order-by-only-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_1.sweetness) AS avg_1,",
                    "               count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY anon_1.avg_1 ASC",
                ],
                "order-by-only-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_1.sweetness) AS avg_1,",
                    "               count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY anon_1.avg_1 ASC",
                ],
                "filtered-and-selected-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.count_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " WHERE anon_1.count_1 > %(param_1)s",
                    " ORDER BY color.id ASC",
                ],
                "filtered-and-selected-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, ?) > ?",
                    " ORDER BY color.id ASC",
                ],
                "filtered-and-selected-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, %s) > %s",
                    " ORDER BY color.id ASC",
                ],
                "nested-filter-only-postgresql": [
                    'SELECT "group".id,',
                    "       color_1.id AS id_1,",
                    "       color_1.id AS group__color__id,",
                    "       anon_1.sum_1",
                    '  FROM "group" AS "group"',
                    "  JOIN color AS color_1",
                    '    ON color_1.id = "group".color_id',
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color_1.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " WHERE anon_1.count_1 > %(param_1)s",
                    ' ORDER BY "group".id ASC,',
                    "          color_1.id ASC",
                ],
                "nested-filter-only-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    '       ) SELECT "group".id,',
                    "       color_1.id AS id_1,",
                    "       color_1.id AS group__color__id,",
                    "       anon_1.sum_1",
                    '  FROM "group" AS "group"',
                    "  JOIN color AS color_1",
                    '    ON color_1.id = "group".color_id',
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color_1.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, ?) > ?",
                    ' ORDER BY "group".id ASC,',
                    "          color_1.id ASC",
                ],
                "nested-filter-only-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               sum(fruit_1.sweetness) AS sum_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT `group`.id,",
                    "       color_1.id AS id_1,",
                    "       color_1.id AS group__color__id,",
                    "       anon_1.sum_1",
                    "  FROM `group` AS `group`",
                    " INNER JOIN color AS color_1",
                    "    ON color_1.id = `group`.color_id",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color_1.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, %s) > %s",
                    " ORDER BY `group`.id ASC,",
                    "          color_1.id ASC",
                ],
            }
        )[request.node.callspec.id]
    )


@_DIALECTS
@pytest.mark.parametrize(
    "query",
    [
        pytest.param(
            "{ colors(orderBy: { fruitsAggregate: { count: ASC } }) { fruitsAggregate { count } } }",
            id="output-order-by",
        ),
        pytest.param(
            "{ colors(filter: { fruitsAggregate: { count: { predicate: { gt: 0 } } } }) { fruitsAggregate { count } } }",
            id="output-filter",
        ),
        pytest.param(
            """{ colors(filter: { fruitsAggregate: { count: { predicate: { gt: 0 } } } },
                orderBy: { fruitsAggregate: { avg: { sweetness: ASC } } }) { fruits { id } } }""",
            id="filter-order-by",
        ),
        pytest.param(
            """{ colors(filter: { fruitsAggregate: { avg: { arguments: [sweetness] predicate: { gt: 0 } } } },
                orderBy: { fruitsAggregate: { avg: { sweetness: ASC } } }) { fruits { id } } }""",
            id="filter-order-by-same-aggregation",
        ),
        pytest.param(
            "{ colors { fruitsAggregate { max { sweetness name } } } }",
            id="output-multiple-aggregations",
        ),
        pytest.param(
            """{ colors(filter: { fruitsAggregate: {
                sum: { arguments: [sweetness], predicate: { gt: 0 } },
                avg: { arguments: [sweetness], predicate: { gt: 0 } } } }) { fruits { id } } }""",
            id="filter-multiple-aggregations",
        ),
        pytest.param(
            """{ colors(orderBy: { fruitsAggregate: { sum: { sweetness: ASC }, avg: { sweetness: ASC } } }) {
                fruits { id } } }""",
            id="order-by-multiple-aggregations",
        ),
        pytest.param(
            """{ colors(orderBy: { fruitsAggregate: { sum: { sweetness: ASC } } }) {
                id fruitsAggregate { count } } }""",
            id="order-by-and-selected-functions",
        ),
    ],
)
def test_filter_order_select_share_one_join(dialect_name: str, query: str, request: pytest.FixtureRequest) -> None:
    """Filtering, ordering and selecting functions of one aggregation compute them in a single LATERAL or CTE."""
    assert (
        plan_sql(query, dialect_name)
        == snapshot(
            {
                "output-order-by-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.count_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " ORDER BY anon_1.count_1 ASC",
                ],
                "output-order-by-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY coalesce(anon_1.count_1, ?) ASC",
                ],
                "output-order-by-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY coalesce(anon_1.count_1, %s) ASC",
                ],
                "output-filter-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.count_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " WHERE anon_1.count_1 > %(param_1)s",
                    " ORDER BY color.id ASC",
                ],
                "output-filter-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, ?) > ?",
                    " ORDER BY color.id ASC",
                ],
                "output-filter-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " WHERE coalesce(anon_1.count_1, %s) > %s",
                    " ORDER BY color.id ASC",
                ],
                "filter-order-by-postgresql": [
                    "SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1,",
                    "               avg(fruit_2.sweetness) AS avg_1",
                    "          FROM fruit AS fruit_2",
                    "         WHERE color.id = fruit_2.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.count_1 > %(param_1)s",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-order-by-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               avg(fruit_2.sweetness) AS avg_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE coalesce(anon_1.count_1, ?) > ?",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-order-by-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               avg(fruit_2.sweetness) AS avg_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE coalesce(anon_1.count_1, %s) > %s",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-order-by-same-aggregation-postgresql": [
                    "SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1",
                    "          FROM fruit AS fruit_2",
                    "         WHERE color.id = fruit_2.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.avg_1 > %(param_1)s",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-order-by-same-aggregation-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.avg_1 > ?",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-order-by-same-aggregation-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.avg_1 > %s",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "output-multiple-aggregations-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.max_1,",
                    "       anon_1.max_2",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT max(fruit_1.sweetness) AS max_1,",
                    "               max(fruit_1.name) AS max_2",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " ORDER BY color.id ASC",
                ],
                "output-multiple-aggregations-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT max(fruit_1.sweetness) AS max_1,",
                    "               max(fruit_1.name) AS max_2,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       anon_1.max_1,",
                    "       anon_1.max_2",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY color.id ASC",
                ],
                "output-multiple-aggregations-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT max(fruit_1.sweetness) AS max_1,",
                    "               max(fruit_1.name) AS max_2,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       anon_1.max_1,",
                    "       anon_1.max_2",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY color.id ASC",
                ],
                "filter-multiple-aggregations-postgresql": [
                    "SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               sum(fruit_2.sweetness) AS sum_1",
                    "          FROM fruit AS fruit_2",
                    "         WHERE color.id = fruit_2.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.avg_1 > %(param_1)s",
                    "   AND anon_1.sum_1 > %(param_2)s",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-multiple-aggregations-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               sum(fruit_2.sweetness) AS sum_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.avg_1 > ?",
                    "   AND anon_1.sum_1 > ?",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC",
                ],
                "filter-multiple-aggregations-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               sum(fruit_2.sweetness) AS sum_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " WHERE anon_1.avg_1 > %s",
                    "   AND anon_1.sum_1 > %s",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC",
                ],
                "order-by-multiple-aggregations-postgresql": [
                    "SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               sum(fruit_2.sweetness) AS sum_1",
                    "          FROM fruit AS fruit_2",
                    "         WHERE color.id = fruit_2.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          anon_1.sum_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "order-by-multiple-aggregations-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               sum(fruit_2.sweetness) AS sum_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          anon_1.sum_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "order-by-multiple-aggregations-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT avg(fruit_2.sweetness) AS avg_1,",
                    "               sum(fruit_2.sweetness) AS sum_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    " ORDER BY anon_1.avg_1 ASC,",
                    "          anon_1.sum_1 ASC,",
                    "          fruit_1.id ASC",
                ],
                "order-by-and-selected-functions-postgresql": [
                    "SELECT color.id,",
                    "       anon_1.count_1",
                    "  FROM color AS color",
                    "  JOIN LATERAL (",
                    "        SELECT sum(fruit_1.sweetness) AS sum_1,",
                    "               count(*) AS count_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    " ORDER BY anon_1.sum_1 ASC",
                ],
                "order-by-and-selected-functions-sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT sum(fruit_1.sweetness) AS sum_1,",
                    "               count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY anon_1.sum_1 ASC",
                ],
                "order-by-and-selected-functions-mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT sum(fruit_1.sweetness) AS sum_1,",
                    "               count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT color.id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color.id = anon_1.color_id",
                    " ORDER BY anon_1.sum_1 ASC",
                ],
            }
        )[request.node.callspec.id]
    )


@_DIALECTS
def test_relation_level_selects_its_aggregate(dialect_name: str) -> None:
    """An aggregate selected under a relation is computed per related row, correlated to the relation's alias."""
    lines = plan_sql("{ groups { color { fruitsAggregate { count } } } }", dialect_name)

    assert (
        lines
        == snapshot(
            {
                "postgresql": [
                    'SELECT "group".id,',
                    "       color_1.id AS id_1,",
                    "       color_1.id AS group__color__id,",
                    "       anon_1.count_1",
                    '  FROM "group" AS "group"',
                    "  LEFT OUTER JOIN color AS color_1",
                    '    ON color_1.id = "group".color_id',
                    "  JOIN LATERAL (",
                    "        SELECT count(*) AS count_1",
                    "          FROM fruit AS fruit_1",
                    "         WHERE color_1.id = fruit_1.color_id",
                    "       ) AS anon_1",
                    "    ON TRUE",
                    ' ORDER BY "group".id ASC,',
                    "          color_1.id ASC",
                ],
                "sqlite": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    '       ) SELECT "group".id,',
                    "       color_1.id AS id_1,",
                    "       color_1.id AS group__color__id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1",
                    '  FROM "group" AS "group"',
                    "  LEFT OUTER JOIN color AS color_1",
                    '    ON color_1.id = "group".color_id',
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color_1.id = anon_1.color_id",
                    ' ORDER BY "group".id ASC,',
                    "          color_1.id ASC",
                ],
                "mysql": [
                    "WITH anon_1 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_1.color_id AS color_id",
                    "          FROM fruit AS fruit_1",
                    "         WHERE fruit_1.color_id IS NOT NULL",
                    "         GROUP BY fruit_1.color_id",
                    "       ) SELECT `group`.id,",
                    "       color_1.id AS id_1,",
                    "       color_1.id AS group__color__id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1",
                    "  FROM `group` AS `group`",
                    "  LEFT OUTER JOIN color AS color_1",
                    "    ON color_1.id = `group`.color_id",
                    "  LEFT OUTER JOIN anon_1",
                    "    ON color_1.id = anon_1.color_id",
                    " ORDER BY `group`.id ASC,",
                    "          color_1.id ASC",
                ],
            }
        )[dialect_name]
    )


@pytest.mark.parametrize("dialect_name", ["sqlite", "mysql"])
def test_aggregate_at_two_levels_shares_one_grouped_cte(dialect_name: str) -> None:
    """Without LATERAL, one aggregate selected at two levels joins one grouped CTE, once per level."""
    lines = plan_sql(
        "{ colors { fruitsAggregate { count } fruits { color { fruitsAggregate { count } } } } }", dialect_name
    )

    assert (
        lines
        == snapshot(
            {
                "sqlite": [
                    "WITH anon_2 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1,",
                    "       color_1.id AS id_2,",
                    "       color_1.id AS fruits__color__id,",
                    "       coalesce(anon_1.count_1, ?) AS coalesce_1,",
                    "       coalesce(anon_2.count_1, ?) AS coalesce_3",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    "  LEFT OUTER JOIN anon_2",
                    "    ON color.id = anon_2.color_id",
                    "  LEFT OUTER JOIN color AS color_1",
                    "    ON color_1.id = fruit_1.color_id",
                    "  LEFT OUTER JOIN anon_2 AS anon_1",
                    "    ON color_1.id = anon_1.color_id",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC,",
                    "          color_1.id ASC",
                ],
                "mysql": [
                    "WITH anon_2 AS (",
                    "        SELECT count(*) AS count_1,",
                    "               fruit_2.color_id AS color_id",
                    "          FROM fruit AS fruit_2",
                    "         WHERE fruit_2.color_id IS NOT NULL",
                    "         GROUP BY fruit_2.color_id",
                    "       ) SELECT color.id,",
                    "       fruit_1.id AS id_1,",
                    "       color_1.id AS id_2,",
                    "       color_1.id AS fruits__color__id,",
                    "       coalesce(anon_1.count_1, %s) AS coalesce_1,",
                    "       coalesce(anon_2.count_1, %s) AS coalesce_3",
                    "  FROM color AS color",
                    "  LEFT OUTER JOIN fruit AS fruit_1",
                    "    ON color.id = fruit_1.color_id",
                    "  LEFT OUTER JOIN anon_2",
                    "    ON color.id = anon_2.color_id",
                    "  LEFT OUTER JOIN color AS color_1",
                    "    ON color_1.id = fruit_1.color_id",
                    "  LEFT OUTER JOIN anon_2 AS anon_1",
                    "    ON color_1.id = anon_1.color_id",
                    " ORDER BY color.id ASC,",
                    "          fruit_1.id ASC,",
                    "          color_1.id ASC",
                ],
            }
        )[dialect_name]
    )
