from __future__ import annotations

import re
from typing import TYPE_CHECKING

import pytest
from sqlalchemy import Column, Date, MetaData, Table, and_
from sqlalchemy.dialects import sqlite as sqlite_dialect

from strawchemy.schema.filters import DateComparison, DateTimeComparison
from strawchemy.schema.filters.inputs import OrderComparison

if TYPE_CHECKING:
    from sqlalchemy import ClauseElement

_DIALECT = sqlite_dialect.dialect()
_DATE_COLUMN = Table("date_filter", MetaData(), Column("value", Date)).c.value

# Conversion letters SQLite gained in 3.44 and 3.46. An unknown letter makes strftime() return NULL, so a
# filter built on one silently matches nothing on older builds (Ubuntu 24.04 LTS ships SQLite 3.45.1).
RECENT_CONVERSION_LETTERS = frozenset("eFIklpPRTuGgUV")

DATE_COMPONENTS = ("year", "month", "day", "week", "week_day", "quarter", "iso_year", "iso_week_day")
TIME_COMPONENTS = ("hour", "minute", "second")


def _compile(statement: ClauseElement) -> str:
    return str(statement.compile(dialect=_DIALECT, compile_kwargs={"literal_binds": True}))


def _order_comparison() -> OrderComparison[int]:
    return OrderComparison(eq=1)  # ty: ignore[unknown-argument]  # fields are generated by comparison_input


@pytest.mark.parametrize(
    ("comparison_type", "components"),
    [(DateComparison, DATE_COMPONENTS), (DateTimeComparison, (*DATE_COMPONENTS, *TIME_COMPONENTS))],
    ids=["date", "datetime"],
)
def test_component_filters_avoid_recent_conversion_letters(
    comparison_type: type[DateComparison], components: tuple[str, ...]
) -> None:
    """Test that component filters compile to strftime() calls any supported SQLite understands."""
    comparison = comparison_type(**{component: _order_comparison() for component in components})
    sql = _compile(and_(*comparison.to_expressions(_DIALECT, _DATE_COLUMN)))

    used = {match.group(1) for match in re.finditer(r"strftime\('%(.)'", sql)}

    assert not used & RECENT_CONVERSION_LETTERS
